[package]
name = "sqlite-logic-test-rs"
version = "0.1.0"
edition = "2021"
authors = ["Jiseok CHOI <jiseok.dev@gmail.com>"]

[dependencies]
eyre = "0.6"
sqlite = "0.30"
sqllogictest = { path = "./sqllogictest-rs/sqllogictest", version = "0.11" }
thiserror = "1"
